### ISSUE TITLE
Missing Layer.h build error

### ISSUE THREAD

**Issue by echamberlain** [pixelmatix/SmartMatrix_Fadecandy#2]
Hello,

When I try building the project with Arduino 1.6.4, I get the following build error:

Build options changed, rebuilding all
In file included from /var/folders/pl/k011vjrd1nq6_pjv1z8m64ch0000gs/T/build6383163169892983726.tmp/Layer_Fadecandy.cpp:1:0:
/var/folders/pl/k011vjrd1nq6_pjv1z8m64ch0000gs/T/build6383163169892983726.tmp/Layer_Fadecandy.h:4:19: fatal error: Layer.h: No such file or directory
# include <Layer.h>

^
compilation terminated.
Error compiling.

What haven't I setup correctly with my build environment?

**Comment by embedded-creations** [comment]
Hi Eric, you need SmartMatrix Library release 3.0.  The README still says 3.0-b1, but there's an official release available now:
https://github.com/pixelmatix/SmartMatrix/releases

**Comment by echamberlain** [comment]
Yep, my SmartMatrix library was out of date.  Thank you.
